### ISSUE TITLE
generate_config_from_poll should not require config file

### ISSUE THREAD

**Issue by gdesmott** [0xAvier/doodle_processing#10]
This doesn't work:

```console
$ ./main.py --generate_config_from_poll jeux.csv  
Traceback (most recent call last):
  File "/var/home/cassidy/dev/doodle_processing/./main.py", line 28, in <module>
    configuration = Configuration(args.config)
  File "/var/home/cassidy/dev/doodle_processing/src/Configuration.py", line 13, in __init__
    self._parse_config(config_fn)
  File "/var/home/cassidy/dev/doodle_processing/src/Configuration.py", line 33, in _parse_config
    for game_name in list(config['games'].keys()):
  File "/usr/lib64/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'games'
```

but this does:

```console
./main.py --generate_config_from_poll jeux.csv  -c config.ini 
```

We should not require a config file when using `--generate_config_from_poll` as the whole point is to generate this config file.

Btw maybe we should have different executables instead?

**Comment by 0xAvier** [comment]
Cannot reproduce
